apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "stalwart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "stalwart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  secretName: {{ include "stalwart.fullname" . }}-tls

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  dnsNames:
    {{ toYaml .Values.tls.dnsNames | nindent 4 }}

  issuerRef:
    name: {{ include "stalwart.fullname" . }}
