{{- if and .Values.fdbClientCert.enabled .Values.fdbClientCert.openbaoCACert.caBundle }}
---
# Vault/OpenBao CA Certificate Secret
# Provides the CA certificate for verifying the Vault/OpenBao server TLS connection
# Used by External Secrets Operator VaultDynamicSecret generator
# NOTE: This secret is only created if caBundle is provided in values
# If the secret already exists or is managed externally, leave caBundle empty
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fdbClientCert.openbaoCACert.secretName }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.fdbClientCert.openbaoCACert.key }}: {{ .Values.fdbClientCert.openbaoCACert.caBundle }}
{{- end }}
