{{- if .Values.fdbClientCert.enabled }}
---
# Vault/OpenBao CA Certificate Secret
# Provides the CA certificate for verifying the Vault/OpenBao server TLS connection
# Used by External Secrets Operator VaultDynamicSecret generator
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fdbClientCert.openbaoCACert.secretName }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.fdbClientCert.openbaoCACert.key }}: {{ .Values.fdbClientCert.openbaoCACert.caBundle }}
{{- end }}
