{{- if .Values.stalwart.fallbackAdmin.enabled }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (include "stalwart.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stalwart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "stalwart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
stringData:
  username: admin
  {{- if $existingSecret }}
  password: {{ $existingSecret.data.password | b64dec }}
  {{- else }}
  password: {{ randAlphaNum 24 }}
  {{- end }}
{{- end }}
